// <auto-generated />
namespace EF_lesson_3_1_a.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Teams2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teams2));
        
        string IMigrationMetadata.Id
        {
            get { return "201601190853577_Teams2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
